name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        id: node-test
        run: npm test
        
      - name: Archive test Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result
          path: test-results.xml

  code-coverage:
    name: Unit coverage
    runs-on: ubuntu-latest

    needs: unit-testing  # Specify that this job depends on unit-testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test

      - name: Check code coverage
        run: npm run coverage
        continue-on-error: true  # This makes the workflow continue even if this step fails

      - name: Archive test Result
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-result
          path: coverage
          retention-days: 5

  docker-login-build-push:
    name: Docker Login, Build, and Push
    runs-on: ubuntu-latest

    needs: [code-coverage, unit-testing]  # Specify that this job depends on code-coverage and unit-testing

    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
